//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPMS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RoomType
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BedNum { get; set; }
        public string BedSize { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
